### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by darkdark123456** [huanglei0114/hartmann-analyzer#1]
Hello Huang, i  am trying to refactor your project using C++. i am seeing the function code  /**def calculate_2d_height_from_slope()*/. 

I have a question when it comes to the  part of / **Expand in y-direction*/. I wonder if you forgot to add a negative sign, it like this  /**maks_y = dilated_expand_mask_y[1:-2, :] & ~expand_mask_y[1:-2, :]*/  not is  /**maks_y = dilated_expand_mask_y[1:-2, :] & ~expand_mask_y[1:2, :]*/.

Two matrix & operation by rows ,not a matrix & operation with another matrix's one row .

And i see you mask_x calculate  code is   /** mask_x = dilated_expand_mask_x[:, 1:-2] & ~expand_mask_x[:, 1:-2]*/,
two matrix & operation by cols .

Perhaps I misunderstood the code .This part of  function calcualte_2d_height_from_slope()  code.

Thanks.
/**Code &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&/   
    
# Expand in x-direction
    temp_nan_1 = np.full([nrows, 1], np.nan)
    temp_nan_2 = np.full([nrows, 2], np.nan)
    sx2d_ex = np.hstack((temp_nan_1, sx2d, temp_nan_2))
    x2d_ex = np.hstack((temp_nan_1, x2d, temp_nan_2))

    expand_mask_x = np.isnan(sx2d_ex)
    vse = np.array([[1, 1, 0, 1, 0]])

    dilated_expand_mask_x = ndimage.binary_dilation(
        expand_mask_x, structure=vse)
    mask_x = dilated_expand_mask_x[:, 1:-2] & ~expand_mask_x[:, 1:-2]
    

# Expand in y-direction
    temp_nan_1 = np.full([1, ncols], np.nan)
    temp_nan_2 = np.full([2, ncols], np.nan)
    sy2d_ex = np.vstack((temp_nan_1, sy2d, temp_nan_2))
    y2d_ex = np.vstack((temp_nan_1, y2d, temp_nan_2))

    expand_mask_y = np.isnan(sy2d_ex)
    vse = np.array([[1, 1, 0, 1, 0]]).T

    dilated_expand_mask_y = ndimage.binary_dilation(
        expand_mask_y, structure=vse)
    maks_y = dilated_expand_mask_y[1:-2, :] & ~expand_mask_y[1:2, :]  /********question*/

/**&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*/

When i change   maks_y = dilated_expand_mask_y[1:-2, :] & ~expand_mask_y[1:2, :]  to maks_y = dilated_expand_mask_y[1:-2, :] & ~expand_mask_y[1:-2, :] ,i get result  Aberration = 入/43.0 RMS,Strehl ratio (Mahajan's approximation) = 0.9789

**Comment by huanglei0114** [comment]
Thank you for your question!
Yes, you are correct! 

We noticed this typo (bug and some others) in this function in another project but forgot to update it here. 
The function calculate_2d_height_from_slope() has just been updated. 

Thank you one more time!
